name: C/C++ CI

on: [push, pull_request_target, pull_request_review, pull_request]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2    
    - name: make
      run: make
    - name: check
      run: make run

